name: 1-hour-cron

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest data
        run: |
          curl --request PUT \
          --url '${{ secrets.FETCH_URL }}' \
          --header 'auth: ${{ secrets.SECRET_KEY }}'
